on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  use-in-a-client-project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]    
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Pack our shareable config
        run: |
          mkdir ${{ runner.temp }}/packed
          npm pack --pack-destination ${{ runner.temp }}/packed
      
      - name: Create a client project
        working-directory: ${{ runner.temp }}
        run: |
          mkdir some-project
          cd some-project
          npm init -y
          npm install --save eslint
          touch index.js

      - name: Install our config in the client project
        working-directory: ${{ runner.temp }}/some-project
        run: |
          npm install --save ../packed/*.tgz

      - name: Use shareable config (also checks peer dependencies)
        working-directory: ${{ runner.temp }}/some-project
        run: |
          echo '{ "extends": "pa11y" }' > eslint.config.js
          npx --no eslint .
